console.clear()

// const soma = (n1, n2) => {
//     if (n1 < 0 || n2 < 0){
//         throw RangeError('Sim, passa um numero maior q 0 ai')
//     }
//     return n1 + n2
// }


// console.log(soma(2, 5));


// TRY CATCH
// const soma = (n1, n2) => {
//     return n1 + n2 + n3
// }


// try {
//     console.log(soma(2, 5));
// } catch (error) {
//     console.log('Tipo\n', error.name, '\n')
//     console.log('Mensagem\n', error.message, '\n')
//     console.log('Stack\n', error.stack, '\n')
// }

